// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiPryntWeb.Models._Negocio;

#nullable disable

namespace ServiPryntWeb.Migrations
{
    [DbContext(typeof(Negocio))]
    [Migration("20240619183748_CrearEntidadProducto")]
    partial class CrearEntidadProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Impresoras", b =>
                {
                    b.Property<int>("IdImpresora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdMarca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pdf")
                        .HasColumnType("TEXT");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tinta")
                        .HasColumnType("TEXT");

                    b.HasKey("IdImpresora");

                    b.HasIndex("IdMarca");

                    b.ToTable("Impresoras");
                });

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Marcas", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreMarca")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Ofertas", b =>
                {
                    b.Property<int>("IdImpresora")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdImpresora");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Impresoras", b =>
                {
                    b.HasOne("ServiPryntWeb.Models.Entidades.Marcas", "Marca")
                        .WithMany("Impresoras")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Ofertas", b =>
                {
                    b.HasOne("ServiPryntWeb.Models.Entidades.Impresoras", "Impresoras")
                        .WithOne("Oferta")
                        .HasForeignKey("ServiPryntWeb.Models.Entidades.Ofertas", "IdImpresora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impresoras");
                });

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Impresoras", b =>
                {
                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("ServiPryntWeb.Models.Entidades.Marcas", b =>
                {
                    b.Navigation("Impresoras");
                });
#pragma warning restore 612, 618
        }
    }
}
