// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NascarPage;

#nullable disable

namespace NascarPage.Migrations
{
    [DbContext(typeof(Negocio))]
    [Migration("20241004035750_NoticiasFormFile")]
    partial class NoticiasFormFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("NascarPage.Entitys.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<int>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PilotoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("PilotoId")
                        .IsUnique();

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Foto = "",
                            MarcaId = 3,
                            PilotoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 4
                        },
                        new
                        {
                            Id = 5,
                            Foto = "",
                            MarcaId = 3,
                            PilotoId = 5
                        },
                        new
                        {
                            Id = 6,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 6
                        },
                        new
                        {
                            Id = 7,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 7
                        },
                        new
                        {
                            Id = 8,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 8
                        },
                        new
                        {
                            Id = 9,
                            Foto = "",
                            MarcaId = 3,
                            PilotoId = 9
                        },
                        new
                        {
                            Id = 10,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 10
                        },
                        new
                        {
                            Id = 11,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 11
                        },
                        new
                        {
                            Id = 12,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 12
                        },
                        new
                        {
                            Id = 13,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 13
                        },
                        new
                        {
                            Id = 14,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 14
                        },
                        new
                        {
                            Id = 15,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 15
                        },
                        new
                        {
                            Id = 16,
                            Foto = "",
                            MarcaId = 3,
                            PilotoId = 16
                        },
                        new
                        {
                            Id = 17,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 17
                        },
                        new
                        {
                            Id = 18,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 18
                        },
                        new
                        {
                            Id = 19,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 19
                        },
                        new
                        {
                            Id = 20,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 20
                        },
                        new
                        {
                            Id = 21,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 21
                        },
                        new
                        {
                            Id = 22,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 22
                        },
                        new
                        {
                            Id = 23,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 23
                        },
                        new
                        {
                            Id = 24,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 24
                        },
                        new
                        {
                            Id = 25,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 25
                        },
                        new
                        {
                            Id = 26,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 26
                        },
                        new
                        {
                            Id = 27,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 27
                        },
                        new
                        {
                            Id = 28,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 28
                        },
                        new
                        {
                            Id = 29,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 29
                        },
                        new
                        {
                            Id = 30,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 30
                        },
                        new
                        {
                            Id = 31,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 31
                        },
                        new
                        {
                            Id = 32,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 32
                        },
                        new
                        {
                            Id = 33,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 33
                        },
                        new
                        {
                            Id = 34,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 34
                        },
                        new
                        {
                            Id = 35,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 35
                        },
                        new
                        {
                            Id = 36,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 36
                        },
                        new
                        {
                            Id = 37,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 37
                        },
                        new
                        {
                            Id = 38,
                            Foto = "",
                            MarcaId = 4,
                            PilotoId = 38
                        },
                        new
                        {
                            Id = 39,
                            Foto = "",
                            MarcaId = 1,
                            PilotoId = 39
                        },
                        new
                        {
                            Id = 40,
                            Foto = "",
                            MarcaId = 2,
                            PilotoId = 40
                        });
                });

            modelBuilder.Entity("NascarPage.Entitys.Calendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadDeEventos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventoActual")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Calendario");
                });

            modelBuilder.Entity("NascarPage.Entitys.Campeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoCampeon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PilotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PilotoId");

                    b.ToTable("Campeones");
                });

            modelBuilder.Entity("NascarPage.Entitys.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Evento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Laps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Led")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Piloto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Qual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Start")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("NascarPage.Entitys.Galeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoDos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoTres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ronda")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Galeria");
                });

            modelBuilder.Entity("NascarPage.Entitys.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Foto = "",
                            Nombre = "Chevrolet"
                        },
                        new
                        {
                            Id = 2,
                            Foto = "",
                            Nombre = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Foto = "",
                            Nombre = "Dodge"
                        },
                        new
                        {
                            Id = 4,
                            Foto = "",
                            Nombre = "Toyota"
                        });
                });

            modelBuilder.Entity("NascarPage.Entitys.Nacionalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nacionalidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bandera = "",
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            Id = 2,
                            Bandera = "",
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = 3,
                            Bandera = "",
                            Nombre = "Inglaterra"
                        },
                        new
                        {
                            Id = 4,
                            Bandera = "",
                            Nombre = "Mexico"
                        },
                        new
                        {
                            Id = 5,
                            Bandera = "",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 6,
                            Bandera = "",
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = 7,
                            Bandera = "",
                            Nombre = "Italia"
                        },
                        new
                        {
                            Id = 8,
                            Bandera = "",
                            Nombre = "Dinamarca"
                        });
                });

            modelBuilder.Entity("NascarPage.Entitys.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalles")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("NascarPage.Entitys.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Campeonatos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarrerasGanadas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnActivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoPiloto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NacionalidadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Poles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Top10s")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Top5s")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NacionalidadId");

                    b.ToTable("Pilotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Campeonatos = 0,
                            CarrerasGanadas = 2,
                            Edad = 28,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Milo Davis",
                            Numero = "00",
                            Poles = 4,
                            Top10s = 19,
                            Top5s = 10
                        },
                        new
                        {
                            Id = 2,
                            Campeonatos = 2,
                            CarrerasGanadas = 49,
                            Edad = 40,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Ryan Smith",
                            Numero = "1",
                            Poles = 37,
                            Top10s = 153,
                            Top5s = 108
                        },
                        new
                        {
                            Id = 3,
                            Campeonatos = 0,
                            CarrerasGanadas = 8,
                            Edad = 39,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 2,
                            Nombre = "Hans Muller",
                            Numero = "2",
                            Poles = 1,
                            Top10s = 59,
                            Top5s = 24
                        },
                        new
                        {
                            Id = 4,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 22,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Jim Anderson",
                            Numero = "5",
                            Poles = 0,
                            Top10s = 2,
                            Top5s = 0
                        },
                        new
                        {
                            Id = 5,
                            Campeonatos = 2,
                            CarrerasGanadas = 31,
                            Edad = 32,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Zack Taylor",
                            Numero = "7",
                            Poles = 43,
                            Top10s = 90,
                            Top5s = 67
                        },
                        new
                        {
                            Id = 6,
                            Campeonatos = 0,
                            CarrerasGanadas = 4,
                            Edad = 27,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Ethan Brown",
                            Numero = "9",
                            Poles = 2,
                            Top10s = 23,
                            Top5s = 11
                        },
                        new
                        {
                            Id = 7,
                            Campeonatos = 0,
                            CarrerasGanadas = 2,
                            Edad = 32,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Michael Mrucz",
                            Numero = "10",
                            Poles = 2,
                            Top10s = 8,
                            Top5s = 4
                        },
                        new
                        {
                            Id = 8,
                            Campeonatos = 0,
                            CarrerasGanadas = 7,
                            Edad = 31,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Dave Seth",
                            Numero = "11",
                            Poles = 10,
                            Top10s = 28,
                            Top5s = 16
                        },
                        new
                        {
                            Id = 9,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 24,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 3,
                            Nombre = "Roger Moore",
                            Numero = "12",
                            Poles = 1,
                            Top10s = 5,
                            Top5s = 2
                        },
                        new
                        {
                            Id = 10,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 23,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Philipp Harrinson",
                            Numero = "14",
                            Poles = 0,
                            Top10s = 3,
                            Top5s = 0
                        },
                        new
                        {
                            Id = 11,
                            Campeonatos = 1,
                            CarrerasGanadas = 27,
                            Edad = 38,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 4,
                            Nombre = "Daniel Suarez",
                            Numero = "15",
                            Poles = 17,
                            Top10s = 60,
                            Top5s = 43
                        },
                        new
                        {
                            Id = 12,
                            Campeonatos = 0,
                            CarrerasGanadas = 3,
                            Edad = 39,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 5,
                            Nombre = "Agustin Canapino",
                            Numero = "16",
                            Poles = 7,
                            Top10s = 33,
                            Top5s = 17
                        },
                        new
                        {
                            Id = 13,
                            Campeonatos = 0,
                            CarrerasGanadas = 1,
                            Edad = 26,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Kenny Douglas",
                            Numero = "17",
                            Poles = 2,
                            Top10s = 10,
                            Top5s = 4
                        },
                        new
                        {
                            Id = 14,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 21,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Marnie Miller",
                            Numero = "18",
                            Poles = 0,
                            Top10s = 0,
                            Top5s = 0
                        },
                        new
                        {
                            Id = 15,
                            Campeonatos = 0,
                            CarrerasGanadas = 3,
                            Edad = 27,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Matt McGlovin",
                            Numero = "21",
                            Poles = 9,
                            Top10s = 21,
                            Top5s = 10
                        },
                        new
                        {
                            Id = 16,
                            Campeonatos = 0,
                            CarrerasGanadas = 5,
                            Edad = 33,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 6,
                            Nombre = "Pierre Lefevre",
                            Numero = "22",
                            Poles = 3,
                            Top10s = 39,
                            Top5s = 20
                        },
                        new
                        {
                            Id = 17,
                            Campeonatos = 6,
                            CarrerasGanadas = 97,
                            Edad = 48,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Jack Miller",
                            Numero = "24",
                            Poles = 53,
                            Top10s = 270,
                            Top5s = 183
                        },
                        new
                        {
                            Id = 18,
                            Campeonatos = 0,
                            CarrerasGanadas = 1,
                            Edad = 34,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Emmet Wilson",
                            Numero = "27",
                            Poles = 0,
                            Top10s = 14,
                            Top5s = 6
                        },
                        new
                        {
                            Id = 19,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 29,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Michael Schmidt",
                            Numero = "29",
                            Poles = 0,
                            Top10s = 17,
                            Top5s = 9
                        },
                        new
                        {
                            Id = 20,
                            Campeonatos = 0,
                            CarrerasGanadas = 8,
                            Edad = 36,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Colton Berta",
                            Numero = "31",
                            Poles = 15,
                            Top10s = 34,
                            Top5s = 21
                        },
                        new
                        {
                            Id = 21,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 32,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Thomas Turner",
                            Numero = "32",
                            Poles = 0,
                            Top10s = 6,
                            Top5s = 2
                        },
                        new
                        {
                            Id = 22,
                            Campeonatos = 0,
                            CarrerasGanadas = 1,
                            Edad = 25,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Miles Biffle",
                            Numero = "34",
                            Poles = 2,
                            Top10s = 19,
                            Top5s = 9
                        },
                        new
                        {
                            Id = 23,
                            Campeonatos = 0,
                            CarrerasGanadas = 4,
                            Edad = 30,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Mark Martins",
                            Numero = "36",
                            Poles = 1,
                            Top10s = 53,
                            Top5s = 28
                        },
                        new
                        {
                            Id = 24,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 24,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Noah Sanders",
                            Numero = "37",
                            Poles = 0,
                            Top10s = 8,
                            Top5s = 0
                        },
                        new
                        {
                            Id = 25,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 25,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 3,
                            Nombre = "Reginald Loundon",
                            Numero = "38",
                            Poles = 0,
                            Top10s = 3,
                            Top5s = 1
                        },
                        new
                        {
                            Id = 26,
                            Campeonatos = 3,
                            CarrerasGanadas = 13,
                            Edad = 43,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 8,
                            Nombre = "Kevin Magnussen",
                            Numero = "39",
                            Poles = 21,
                            Top10s = 47,
                            Top5s = 31
                        },
                        new
                        {
                            Id = 27,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 27,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Scott Gilliham",
                            Numero = "42",
                            Poles = 0,
                            Top10s = 5,
                            Top5s = 1
                        },
                        new
                        {
                            Id = 28,
                            Campeonatos = 0,
                            CarrerasGanadas = 1,
                            Edad = 34,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Oliver Cook",
                            Numero = "47",
                            Poles = 0,
                            Top10s = 12,
                            Top5s = 6
                        },
                        new
                        {
                            Id = 29,
                            Campeonatos = 0,
                            CarrerasGanadas = 21,
                            Edad = 30,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 3,
                            Nombre = "Lewis Hammersmith",
                            Numero = "48",
                            Poles = 40,
                            Top10s = 56,
                            Top5s = 36
                        },
                        new
                        {
                            Id = 30,
                            Campeonatos = 0,
                            CarrerasGanadas = 6,
                            Edad = 36,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Carl Menard",
                            Numero = "50",
                            Poles = 8,
                            Top10s = 26,
                            Top5s = 11
                        },
                        new
                        {
                            Id = 31,
                            Campeonatos = 0,
                            CarrerasGanadas = 1,
                            Edad = 29,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Tony Montana",
                            Numero = "55",
                            Poles = 2,
                            Top10s = 22,
                            Top5s = 7
                        },
                        new
                        {
                            Id = 32,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 24,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 7,
                            Nombre = "Pipo Argenti",
                            Numero = "56",
                            Poles = 0,
                            Top10s = 1,
                            Top5s = 0
                        },
                        new
                        {
                            Id = 33,
                            Campeonatos = 0,
                            CarrerasGanadas = 1,
                            Edad = 35,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Henry Brooks",
                            Numero = "71",
                            Poles = 1,
                            Top10s = 4,
                            Top5s = 2
                        },
                        new
                        {
                            Id = 34,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 33,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Chad Pepper",
                            Numero = "73",
                            Poles = 1,
                            Top10s = 20,
                            Top5s = 4
                        },
                        new
                        {
                            Id = 35,
                            Campeonatos = 3,
                            CarrerasGanadas = 35,
                            Edad = 31,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Santino Boscatto",
                            Numero = "77",
                            Poles = 29,
                            Top10s = 69,
                            Top5s = 59
                        },
                        new
                        {
                            Id = 36,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 28,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Quinn Simons",
                            Numero = "81",
                            Poles = 0,
                            Top10s = 7,
                            Top5s = 2
                        },
                        new
                        {
                            Id = 37,
                            Campeonatos = 0,
                            CarrerasGanadas = 4,
                            Edad = 36,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 7,
                            Nombre = "Marco Rossi",
                            Numero = "83",
                            Poles = 6,
                            Top10s = 40,
                            Top5s = 21
                        },
                        new
                        {
                            Id = 38,
                            Campeonatos = 0,
                            CarrerasGanadas = 0,
                            Edad = 26,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Benjamin Owen",
                            Numero = "87",
                            Poles = 0,
                            Top10s = 3,
                            Top5s = 0
                        },
                        new
                        {
                            Id = 39,
                            Campeonatos = 0,
                            CarrerasGanadas = 13,
                            Edad = 29,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Harry Mcqueen",
                            Numero = "88",
                            Poles = 22,
                            Top10s = 41,
                            Top5s = 30
                        },
                        new
                        {
                            Id = 40,
                            Campeonatos = 1,
                            CarrerasGanadas = 17,
                            Edad = 32,
                            EnActivo = true,
                            FotoPiloto = "",
                            NacionalidadId = 1,
                            Nombre = "Cole Anderson",
                            Numero = "99",
                            Poles = 25,
                            Top10s = 51,
                            Top5s = 29
                        });
                });

            modelBuilder.Entity("NascarPage.Entitys.Pista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disputada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Distancia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnElCalendario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoPrimaria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoSecundaria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoTerciaria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vueltas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Orden")
                        .IsUnique();

                    b.ToTable("Pistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Daytona 500",
                            Orden = 1,
                            Vueltas = 200
                        },
                        new
                        {
                            Id = 2,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "California 500",
                            Orden = 2,
                            Vueltas = 250
                        },
                        new
                        {
                            Id = 3,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "California Night 600",
                            Orden = 3,
                            Vueltas = 275
                        },
                        new
                        {
                            Id = 4,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Darlington 500",
                            Orden = 4,
                            Vueltas = 367
                        },
                        new
                        {
                            Id = 5,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Gateway 400",
                            Orden = 5,
                            Vueltas = 267
                        },
                        new
                        {
                            Id = 6,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Martinsville 500",
                            Orden = 6,
                            Vueltas = 500
                        },
                        new
                        {
                            Id = 7,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Atlanta 500",
                            Orden = 7,
                            Vueltas = 325
                        },
                        new
                        {
                            Id = 8,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Atlanta Night 600",
                            Orden = 8,
                            Vueltas = 350
                        },
                        new
                        {
                            Id = 9,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Watkins Glen 220",
                            Orden = 9,
                            Vueltas = 90
                        },
                        new
                        {
                            Id = 10,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Dover 400",
                            Orden = 10,
                            Vueltas = 267
                        },
                        new
                        {
                            Id = 11,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Kansas 400",
                            Orden = 11,
                            Vueltas = 267
                        },
                        new
                        {
                            Id = 12,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Las Vegas 400",
                            Orden = 12,
                            Vueltas = 267
                        },
                        new
                        {
                            Id = 13,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Twin Ring 400",
                            Orden = 13,
                            Vueltas = 250
                        },
                        new
                        {
                            Id = 14,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Bristol Dirty Night 500",
                            Orden = 14,
                            Vueltas = 500
                        },
                        new
                        {
                            Id = 15,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Indianapolis 400",
                            Orden = 15,
                            Vueltas = 160
                        },
                        new
                        {
                            Id = 16,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Nashville 400",
                            Orden = 16,
                            Vueltas = 325
                        },
                        new
                        {
                            Id = 17,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Nazareth 400",
                            Orden = 17,
                            Vueltas = 325
                        },
                        new
                        {
                            Id = 18,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Infineon 350k",
                            Orden = 18,
                            Vueltas = 112
                        },
                        new
                        {
                            Id = 19,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Rockingham 350",
                            Orden = 19,
                            Vueltas = 393
                        },
                        new
                        {
                            Id = 20,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Phoenix 500k",
                            Orden = 20,
                            Vueltas = 312
                        },
                        new
                        {
                            Id = 21,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "New Hampshire 400",
                            Orden = 21,
                            Vueltas = 312
                        },
                        new
                        {
                            Id = 22,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Pocono 500",
                            Orden = 22,
                            Vueltas = 200
                        },
                        new
                        {
                            Id = 23,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Richmond 400",
                            Orden = 23,
                            Vueltas = 400
                        },
                        new
                        {
                            Id = 24,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Evergreen 400",
                            Orden = 24,
                            Vueltas = 450
                        },
                        new
                        {
                            Id = 25,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Talladega 500",
                            Orden = 25,
                            Vueltas = 188
                        },
                        new
                        {
                            Id = 26,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Milwaukee Night 450",
                            Orden = 26,
                            Vueltas = 350
                        },
                        new
                        {
                            Id = 27,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Chicagoland 400",
                            Orden = 27,
                            Vueltas = 267
                        },
                        new
                        {
                            Id = 28,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Iowa Night 400",
                            Orden = 28,
                            Vueltas = 400
                        },
                        new
                        {
                            Id = 29,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Kentucky Speedway 400",
                            Orden = 29,
                            Vueltas = 267
                        },
                        new
                        {
                            Id = 30,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Michigan 400",
                            Orden = 30,
                            Vueltas = 200
                        },
                        new
                        {
                            Id = 31,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Lowes Night 600",
                            Orden = 31,
                            Vueltas = 400
                        },
                        new
                        {
                            Id = 32,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Bristol 500",
                            Orden = 32,
                            Vueltas = 500
                        },
                        new
                        {
                            Id = 33,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Bristol Night 500",
                            Orden = 33,
                            Vueltas = 500
                        },
                        new
                        {
                            Id = 34,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Texas 500",
                            Orden = 34,
                            Vueltas = 333
                        },
                        new
                        {
                            Id = 35,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Coca Cola 600",
                            Orden = 35,
                            Vueltas = 250
                        },
                        new
                        {
                            Id = 36,
                            Disputada = false,
                            Distancia = "",
                            EnElCalendario = true,
                            FotoPrimaria = "",
                            FotoSecundaria = "",
                            FotoTerciaria = "",
                            Nombre = "Homestead Miami 400 Championship",
                            Orden = 36,
                            Vueltas = 267
                        });
                });

            modelBuilder.Entity("NascarPage.Entitys.PosicionCampeonatoRegular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Behind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DNF")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LapsLead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PilotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Poles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Top10s")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Top5s")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("PilotoId");

                    b.ToTable("TablaPosicionesCampeonatoRegular");
                });

            modelBuilder.Entity("NascarPage.Entitys.PosicionManofactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puntos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId")
                        .IsUnique();

                    b.ToTable("TablaPosicionesManofactura");
                });

            modelBuilder.Entity("NascarPage.Entitys.PosicionPlayoff", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BehindPlayoff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clasificado12avos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clasificado16avos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clasificado8avos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClasificadoFinal4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PilotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosExtra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosPlayoff")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("PilotoId");

                    b.ToTable("TablaPosicionesPlayoff");
                });

            modelBuilder.Entity("NascarPage.Entitys.Auto", b =>
                {
                    b.HasOne("NascarPage.Entitys.Marca", "Marca")
                        .WithMany("ListaAutos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NascarPage.Entitys.Piloto", "Piloto")
                        .WithOne("Auto")
                        .HasForeignKey("NascarPage.Entitys.Auto", "PilotoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Marca");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("NascarPage.Entitys.Campeon", b =>
                {
                    b.HasOne("NascarPage.Entitys.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("NascarPage.Entitys.Piloto", b =>
                {
                    b.HasOne("NascarPage.Entitys.Nacionalidad", "Nacionalidad")
                        .WithMany("ListaPilotos")
                        .HasForeignKey("NacionalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nacionalidad");
                });

            modelBuilder.Entity("NascarPage.Entitys.PosicionCampeonatoRegular", b =>
                {
                    b.HasOne("NascarPage.Entitys.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NascarPage.Entitys.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("NascarPage.Entitys.PosicionManofactura", b =>
                {
                    b.HasOne("NascarPage.Entitys.Marca", "Marca")
                        .WithOne("PosicionManofactura")
                        .HasForeignKey("NascarPage.Entitys.PosicionManofactura", "MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("NascarPage.Entitys.PosicionPlayoff", b =>
                {
                    b.HasOne("NascarPage.Entitys.PosicionCampeonatoRegular", "Regular")
                        .WithOne("Playoff")
                        .HasForeignKey("NascarPage.Entitys.PosicionPlayoff", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NascarPage.Entitys.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NascarPage.Entitys.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Piloto");

                    b.Navigation("Regular");
                });

            modelBuilder.Entity("NascarPage.Entitys.Marca", b =>
                {
                    b.Navigation("ListaAutos");

                    b.Navigation("PosicionManofactura")
                        .IsRequired();
                });

            modelBuilder.Entity("NascarPage.Entitys.Nacionalidad", b =>
                {
                    b.Navigation("ListaPilotos");
                });

            modelBuilder.Entity("NascarPage.Entitys.Piloto", b =>
                {
                    b.Navigation("Auto")
                        .IsRequired();
                });

            modelBuilder.Entity("NascarPage.Entitys.PosicionCampeonatoRegular", b =>
                {
                    b.Navigation("Playoff")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
